services:
  mongodb:
    image: "mongo:7.0-jammy"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
